[project]
name = "simclr"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "torch",
    "numpy",
    "matplotlib",
    "ms-entropy>=1.5.2",
    "safetensors",
    "streamlit",
]

[dependency-groups]
deploy = [
    "torch",
    "numpy",
    "matplotlib",
    "ms-entropy>=1.5.2",
    "safetensors",
    "streamlit",
]
dev = [
    "cupy-cuda12x>=14.1.1",
    "ipykernel",
    "tqdm",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "httpx",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
