# Streamlit Default Configuration

[server]
port = 8001
baseUrlPath = "cannabinoids"
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
corsAllowedOrigins = ["https://chem.warships.cn", "https://mspredict.com"]

[browser]
gatherUsageStats = false
